POST https://localhost:7118/api/ordenes_envio
content-type: application/json

{
  "IdShipmentOrder": 2,
  "OriginAddress": "Cacheuta 4028",
  "DestinationAddress": "Villanueva 2764",
  "BuyerContact": "3515951448",
  "ShipmentState": "Created",
  "Product": "Xbox",
  "DeliveryMan": "Pepe"
}

###

GET https://localhost:7118/api/ordenes_envio/2
