POST https://localhost:7118/api/ordenes_envio
content-type: application/json

{
  "Origin": {
    "IdAddress": null,
    "Street": "Cacheuta",
    "HouseNumber": 4028,
    "Floor": 1,
    "ApartmentNumber": 1,
    "City": {
      "IdCity": null,
      "Name": "Córdoba"
    }
  },
  "Destination": {
    "IdAddress": null,
    "Street": "Villanueva",
    "HouseNumber": 2764,
    "Floor": null,
    "ApartmentNumber": null,
    "City": {
      "IdCity": null,
      "Name": "Córdoba"
    }
  },
  "Buyer": {
    "IdContact": null,
    "Email": "lucasg18c@gmail.com",
    "Phone": "3515951448"
  },
  "Product": {
    "IdProduct": null,
    "Name": "Xbox series S",
    "Description": "Consola de videojuegos"
  }
}

###

GET https://localhost:7118/api/ordenes_envio/2

###

POST https://localhost:7118/api/repartidores/
content-type: application/json

{
  "IdDeliveryMan": null,
  "FirstName": "Juan",
  "LastName": "Perez"
}

###

GET https://localhost:7118/api/repartidores/

######

DELETE https://localhost:7118/api/repartidores/
content-type: application/json

1
###

POST https://localhost:7118/api/ordenes_envio/2/repartidor
content-type: application/json

1

###

POST https://localhost:7118/api/ordenes_envio/2/entrega
