POST https://dev-qdpsr1z8.us.auth0.com/oauth/token
content-type: application/json

{
  "client_id":"HqjwNGT8uBncYE8g4CBqbELDdUwFaAJB",
  "client_secret":"gKTA4he9k3ARZTj2BEOY0DzK6p0DOCgBYfrMTMdUqSHxUligepaxIfX0hVKfiFAR",
  "audience":"https://oln.com.ar/api/",
  "grant_type":"client_credentials"
  }

###

eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NTczMDYxLCJleHAiOjE2Njg2NTk0NjEsImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Ky6E-A_HkDfbrq7WhEE24Lrj-b9xRvVlMC8PZzfMkTQF0i3QcnOfxk7lN6tJto8R4EaDgpt69AzfvOMg0M8o1TiuBA9Zt8xw5sKorbjK_hO_01UKayNXlI43ibYR6AxjaxHhnKliZAs_6s8WauuSbvLli7bQxaDddXwOdt0nPWugldNDvdq6hHroeBdzV1e_PR_zu92f8KWQiI2X6XOssxIvUs1iztOnbuNqzf6g0PHVqqx0XlxJlYwLUkiqTTH_2PVMh4rTxR0wW5VTluqKk2ca5IqbwAKEvYfNwoCtHkRMr5mnwqn0ehjH7ntf3vZm4hDmTSuXkoHF2sIN_U9yPg

###

POST http://15.228.36.145:8081/api/ordenes_envio
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NjM5OTc1LCJleHAiOjE2Njg3MjYzNzUsImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.sgINItwxpy3FZBdpWxnV564LRLUfrbtB2LTeIIscoCurq8M_XW1-i46GjeV6Y3CMS4iwyg4K1TP_PPi-LBv_ajCTlvpR6z90550H5YqLF2BGAN-usB16QUeVmm6mGIC-JvXCfxIGOsO52PjFgueVxNUG5Qv00ZUSCPfbxMF019KVey8vYcuiXEObtZ7ruTNFFwwQJWy77OosLdNZXeSQiLM67SsF1RKlhTWMj18mH7L2NF7q_wM2lBQbEokmYf6oUwj_3hsIuc-4BwY1xKKENbz6AkLtqVGupGG0ahznppvk1hyH1MRIqVXgdqtkYgTXF1w74t5hXhKJ-uDArstZ7A 
content-type: application/json

{
  "Origin": {
    "IdAddress": null,
    "Street": "Cacheuta",
    "HouseNumber": 4028,
    "Floor": 1,
    "ApartmentNumber": 1,
    "City": {
      "IdCity": null,
      "Name": "Córdoba"
    }
  },
  "Destination": {
    "IdAddress": null,
    "Street": "Villanueva",
    "HouseNumber": 2764,
    "Floor": null,
    "ApartmentNumber": null,
    "City": {
      "IdCity": null,
      "Name": "Córdoba"
    }
  },
  "Buyer": {
    "IdContact": null,
    "Email": "lucasg18c@gmail.com",
    "Phone": "3515951448"
  },
  "Product": {
    "IdProduct": null,
    "Name": "Xbox series S",
    "Description": "Consola de videojuegos"
  }
}

###

GET http://15.228.36.145:8081/api/ordenes_envio/0
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NTc0MTYwLCJleHAiOjE2Njg2NjA1NjAsImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Uq-X-bi_rLu6pHa71D-YYW_5t50i-2TdT3WO12eAbXyjEAmwU57kdTsac-49rdHLA7YlyNpSORlL-YdpebqoJacPsZgWbchIW8pQgcxXuPY_0oJwXj0lehDlSlCpMw7bapzyHOO3pD5MBWgNUaCEqS0JR47QeMkJ6sWkLWJdb0ZVi40ex9s-T4xI2Wg1ayJ8Z8R56oi75gFWrG2D8lg-mjE6AVZYKQejlIH-cLX_H2Ns_WtlzrNh4_A0X1peE0LYEOL2pVl-cDRCJiMa8oYqCXiIRVAXtAfUAS9LtK3Fz06i96XG82TlWpZIlLXVEiN-w13vozcBiPgiIZgaNuqR_A 


###

POST http://15.228.36.145:8081/api/repartidores/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NzEzMTA5LCJleHAiOjE2Njg3OTk1MDksImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Llhg1vYbMob_Ynpx0yLd9FGmd62SBgZcxFY2jepEF_3cpTrXEAhZOpnigt_52qW1bl76GFGfbi_rOnLU0IYYlq_JLpWnJfBVDgfV9jQyVUCsHp_iliw0iTqcmAlREWrKtBzJAQjcDWyGcNpynLCXB-Fox0Fpiqv0mFJR9Va_EciNsGFbHlKQQustwvjmxSRp2g-l67CJ2CWxGjUNgrBlhlvhoVzR3qi2ep8p1iEfY4Py80F-Hx-y6bdZbsFzwURXgHPihuueeHLybYgFGehTOHOKCOzDnggTXjwdIGITbmasSD-CxSN-SVZIsalIhyGWSYZHpATmUmNzKPb40mrkZw 
content-type: application/json

{
  "Nombre": "Lucas",
  "Apellido": "Slavik"
}

###

GET http://15.228.36.145:8081/api/repartidores/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NzEzMTA5LCJleHAiOjE2Njg3OTk1MDksImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Llhg1vYbMob_Ynpx0yLd9FGmd62SBgZcxFY2jepEF_3cpTrXEAhZOpnigt_52qW1bl76GFGfbi_rOnLU0IYYlq_JLpWnJfBVDgfV9jQyVUCsHp_iliw0iTqcmAlREWrKtBzJAQjcDWyGcNpynLCXB-Fox0Fpiqv0mFJR9Va_EciNsGFbHlKQQustwvjmxSRp2g-l67CJ2CWxGjUNgrBlhlvhoVzR3qi2ep8p1iEfY4Py80F-Hx-y6bdZbsFzwURXgHPihuueeHLybYgFGehTOHOKCOzDnggTXjwdIGITbmasSD-CxSN-SVZIsalIhyGWSYZHpATmUmNzKPb40mrkZw 

######

DELETE http://15.228.36.145:8081/api/repartidores/
content-type: application/json

1
###

POST http://15.228.36.145:8081/api/ordenes_envio/0/repartidor
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NTc0MTYwLCJleHAiOjE2Njg2NjA1NjAsImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Uq-X-bi_rLu6pHa71D-YYW_5t50i-2TdT3WO12eAbXyjEAmwU57kdTsac-49rdHLA7YlyNpSORlL-YdpebqoJacPsZgWbchIW8pQgcxXuPY_0oJwXj0lehDlSlCpMw7bapzyHOO3pD5MBWgNUaCEqS0JR47QeMkJ6sWkLWJdb0ZVi40ex9s-T4xI2Wg1ayJ8Z8R56oi75gFWrG2D8lg-mjE6AVZYKQejlIH-cLX_H2Ns_WtlzrNh4_A0X1peE0LYEOL2pVl-cDRCJiMa8oYqCXiIRVAXtAfUAS9LtK3Fz06i96XG82TlWpZIlLXVEiN-w13vozcBiPgiIZgaNuqR_A
content-type: application/json

0

###

POST http://15.228.36.145:8081/api/ordenes_envio/0/entrega
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZVd3NwVUFHcHJ2b1pLVkVfSXJCUyJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZHBzcjF6OC51cy5hdXRoMC5jb20vIiwic3ViIjoiSHFqd05HVDh1Qm5jWUU4ZzRDQnFiRUxEZFV3RmFBSkJAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vb2xuLmNvbS5hci9hcGkvIiwiaWF0IjoxNjY4NTc0MTYwLCJleHAiOjE2Njg2NjA1NjAsImF6cCI6IkhxandOR1Q4dUJuY1lFOGc0Q0JxYkVMRGRVd0ZhQUpCIiwic2NvcGUiOiJyZWFkOmRlbGl2ZXJ5bWFucyB3cml0ZTpkZWxpdmVyeW1hbnMgZGVsZXRlOmRlbGl2ZXJ5bWFucyB3cml0ZTpzaGlwbWVudG9yZGVyIHJlYWQ6c2hpcG1lbnRvcmRlciB3cml0ZTpzaGlwbWVudHN0YXRlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.Uq-X-bi_rLu6pHa71D-YYW_5t50i-2TdT3WO12eAbXyjEAmwU57kdTsac-49rdHLA7YlyNpSORlL-YdpebqoJacPsZgWbchIW8pQgcxXuPY_0oJwXj0lehDlSlCpMw7bapzyHOO3pD5MBWgNUaCEqS0JR47QeMkJ6sWkLWJdb0ZVi40ex9s-T4xI2Wg1ayJ8Z8R56oi75gFWrG2D8lg-mjE6AVZYKQejlIH-cLX_H2Ns_WtlzrNh4_A0X1peE0LYEOL2pVl-cDRCJiMa8oYqCXiIRVAXtAfUAS9LtK3Fz06i96XG82TlWpZIlLXVEiN-w13vozcBiPgiIZgaNuqR_A 

